### PR TITLE
fix: add missing key to check if translated string is different from its id

### PR DESCRIPTION
**Pull request by LiKang6688**
if the translated string is different from its id, we assume translations already exist for the current locale

adding the key 'SNTable.Accessibility.RowsAndColumns' to do that to have a better performance.

### CODE REVIEW

**Comment by haxxmaxx** [comment]
Or just run `registerLocale` once? Or is there some case where we need to rerun it?

**Comment by haxxmaxx** [comment]
> > Or just run `registerLocale` once? Or is there some case where we need to rerun it?
> 
> Object.keys(all).forEach((key) => { translator.add(all[key]); }); only needs to be run once.
> 
> but registerLocale runs every time when we change the language no matter whether we put registerLocale in or out of useEffect.

Ah of course, in that case we need to rerun it sometimes. I guess you can have a separate useEffect for `registerLocale` but that is maybe overkill. Quite nice to get the logic away from index actually

**Comment by haxxmaxx** [comment]
btw do we have any tests on locale files?

**Comment by LiKang6688** [comment]
> btw do we have any tests on locale files?

no, we do not. I will add that in this PR.

**Comment by LiKang6688** [comment]
> btw do we have any tests on locale files?

Done

**Review by haxxmaxx — APPROVED** [review]

**Comment by haxxmaxx** [comment]
I just merged some new translations so you got some enoying conflicts, but feel free to merge when that is fixed

**Pull request merged**
