### PR TITLE
test: ensure the running container is stopped even when a test breaks

### PR DESCRIPTION
**Pull request by LiKang6688**
Use exit tap to ensure the running container `sn-table-playwright` is stopped even when a test breaks.

### CODE REVIEW

**Comment by haxxmaxx** [comment]
Good idea but this means even more duplicate code. The only thing that differs is the update flag. it should be passed as a flag/argument instead.

**Comment by LiKang6688** [comment]
> Good idea but this means even more duplicate code. The only thing that differs is the update flag. it should be passed as a flag/argument instead.

Right, sure, I will do the refactor in the next PR.

**Comment by LiKang6688** [comment]
In that case, there will be only one bash script. What file name do you suggest?

**Comment by haxxmaxx** [comment]
> In that case, there will be only one bash script. What file name do you suggest?

run-rendering-tests works, you are still running them when you update the snapshots

**Comment by haxxmaxx** [comment]
> Right, sure, I will do the refactor in the next PR.

I think you should do it the other way around though. Make it into one file before adding code to both files

**Review by haxxmaxx — APPROVED** [review]

**Pull request merged**
