### PR TITLE
fix: hide rpp select when entering selection mode

### PR DESCRIPTION
**Pull request by haxxmaxx**
Adding a new prop since all the other props stayed the same when entering selection mode

### CODE REVIEW

**Comment by LiKang6688** [comment]
the title should be 'fix: pass isInSelectionMode explicitly'?

**Comment by haxxmaxx** [comment]
> the title should be 'refactor: pass isInSelectionMode explicitly'?

Nope, this is a verifail. without this the pagination content does not update when you start selection mode

**Comment by LiKang6688** [comment]
> > the title should be 'refactor: pass isInSelectionMode explicitly'?
> 
> Nope, this is a verifail. without this the pagination content does not update when you start selection mode

aha, because of memo, selectionsAPI does not change?

**Review by LiKang6688 — APPROVED** [review]

**Comment by haxxmaxx** [comment]
> > > the title should be 'refactor: pass isInSelectionMode explicitly'?
> > 
> > 
> > Nope, this is a verifail. without this the pagination content does not update when you start selection mode
> 
> aha, because of memo, selectionsAPI does not change?

It doesn't, but it never has. Acutally it was the announcer changing everytime before, whenever the useEffect in index ran. Now that is memoed so we need to look at isModal() explicitely

**Pull request merged**
