### PR TITLE
feature: focus the first cell after doing selection confirmation

### PR DESCRIPTION
**Pull request by LiKang6688**
to focus on the first cell of the body after selection confirmation instead of focusing on the first cell of the thead.

### CODE REVIEW

**Comment by haxxmaxx** [comment]
Why? I think we should have the same fallback cell independent of whether you're changing page or confirming selections. This just adds complexity.

**Comment by LiKang6688** [comment]
> Why? I think we should have the same fallback cell independent of whether you're changing page or confirming selections. This just adds complexity.

I think that from the user's perspective, it is a better option. We can get feedback from A360.

**Comment by haxxmaxx** [comment]
> > Why? I think we should have the same fallback cell independent of whether you're changing page or confirming selections. This just adds complexity.
> 
> I think that from the user's perspective, it is a better option. We can get feedback from A360.

Maybe, I've thought about that too. But then always go to the same cell when we reset it. That is just a change [here](https://github.com/qlik-oss/sn-table/blob/main/src/table/cells/handle-cell-focus.js#L34) to `[1, 0]`

**Comment by LiKang6688** [comment]
> That is just a change [here](https://github.com/qlik-oss/sn-table/blob/main/src/table/cells/handle-cell-focus.js#L34) to `[1, 0]`

Are you sure that the change to [1, 0] works? I tried and it did not work. And that's the reason why I handle that in useDidUpdateEffect.

**Comment by haxxmaxx** [comment]
> > That is just a change [here](https://github.com/qlik-oss/sn-table/blob/main/src/table/cells/handle-cell-focus.js#L34) to `[1, 0]`
> 
> Are you sure that the change to [1, 0] works? I tried and it did not work. And that's the reason why I handle that in useDidUpdateEffect.

Nope, I have not tried :) Come to think of it, there is a corner case where you get 0 rows, e.g. making selection in some other chart that results in 0 rows. I think it is better to refocus to the header to make sure there is always a cell with tabindex 0

**Comment by LiKang6688** [comment]
> > > That is just a change [here](https://github.com/qlik-oss/sn-table/blob/main/src/table/cells/handle-cell-focus.js#L34) to `[1, 0]`
> > 
> > 
> > Are you sure that the change to [1, 0] works? I tried and it did not work. And that's the reason why I handle that in useDidUpdateEffect.
> 
> Nope, I have not tried :) Come to think of it, there is a corner case where you get 0 rows, e.g. making selection in some other chart that results in 0 rows. I think it is better to refocus to the header to make sure there is always a cell with tabindex 0

Really good point. I will close the PR then.

**Pull request closed without merging**
