### PR TITLE
feat(translations): UI bus - 2021-10-01

### PR DESCRIPTION
**Pull request by ashrles**
feat(translations): UI bus - 2021-10-01

- Update translations related to: 985f638 - feat(locale): add localization (#263)

- Update translations related to: d3dd750 - feat(translation): all possible to be translated strings (#281)

### CODE REVIEW

**Comment by LiKang6688** [comment]
Hi @ashrles, please look at #303 as well. Thank you! Shall we merge #303 first or it is okay right now?

**Review by HK1112 — APPROVED** [review]
LGTM

**Review by mattgengqlik — APPROVED** [review]
LGTM

**Comment by mattgengqlik** [comment]
> Hi @ashrles, please look at #303 as well. Thank you! Shall we merge #303 first or it is okay right now?

You can merge this first, but the order doesn't matter though. The changes in `en.json` will be picked up in next translation circle.

**Review by oleksiSh — APPROVED** [review]

**Comment by oleksiSh** [comment]
@haxxmaxx can you merge it, please? thanks

**Comment by LiKang6688** [comment]
> @haxxmaxx can you merge it, please? thanks

Sure. Done

**Pull request merged**
