### PR TITLE
feat: viz-1465 add-data-assets-panel

### PR DESCRIPTION
**Pull request by linhnguyen-qlik**
This PR add data-assets-panel to sn-table. The data-assets-panel replaces the current component under Data section in property panel.
- https://github.com/qlik-trial/analytics/pull/285
- https://github.com/qlik-trial/sense-client/pull/21953

### CODE REVIEW

**Comment by haxxmaxx** [comment]
I just merged a refactor of the `ext` file, splitting it up into multiple files. So you change should now be in ext/property-panel/data

**Comment by linhnguyen-qlik** [comment]
> I just merged a refactor of the `ext` file, splitting it up into multiple files. So you change should now be in ext/property-panel/data

I see. I will update.

**Review by mhs30 — APPROVED** [review]

**Comment by mhs30** [comment]
Nice looks good, test is failing tho.

**Comment by haxxmaxx** [comment]
The covarage diff is due to indenting old code, feel free to merge this :)

**Pull request merged**
