### PR TITLE
chore: sort the keys of a package.json file

### PR DESCRIPTION
**Pull request by LiKang6688**

### CODE REVIEW

**Comment by cbt1** [comment]
Do we really need a 3rd party package to "maintain" the sort order? Can we not just run it once locally and be fine with that?

**Comment by LiKang6688** [comment]
> Do we really need a 3rd party package to "maintain" the sort order? Can we not just run it once locally and be fine with that?

it is a prettier plugin that takes effect in `prettier --write .`

**Comment by LiKang6688** [comment]
so we do not need to manually figure out alphabetic order https://github.com/qlik-oss/sn-table/pull/972#discussion_r1158078695_

**Comment by cbt1** [comment]
> so we do not need to manually figure out alphabetic order [#972 (comment)](https://github.com/qlik-oss/sn-table/pull/972#discussion_r1158078695)_

But if you use `yarn add --dev <name-of-package>` they should be added in correct order to the deps list? For the other properties, I don't think we change the scripts or properties often enough

**Comment by LiKang6688** [comment]
> > so we do not need to manually figure out alphabetic order [#972 (comment)](https://github.com/qlik-oss/sn-table/pull/972#discussion_r1158078695)_
> 
> But if you use `yarn add --dev <name-of-package>` they should be added in correct order to the deps list? For the other properties, I don't think we change the scripts or properties often enough

yes, make sense to me

**Comment by LiKang6688** [comment]
> > so we do not need to manually figure out alphabetic order [#972 (comment)](https://github.com/qlik-oss/sn-table/pull/972#discussion_r1158078695)_
> 
> But if you use `yarn add --dev <name-of-package>` they should be added in correct order to the deps list? For the other properties, I don't think we change the scripts or properties often enough

Yes, make sense to me

**Pull request closed without merging**
