### PR TITLE
fix: selection listener memleak

### PR DESCRIPTION
**Pull request by cbt1**
Noticed that while toggling between usePagination a few times an error was logged to console about a possible event memory leak.

Tracked it down to this useEffect that did not properly return the cleanup function.

### CODE REVIEW

**Review by a-m-dev — COMMENTED** [review]
This is a bit confusing to me, more in this perspective of why we need to run `addSelectionListeners` while tearing down the component?

my guess is when you click `usePagination` checkbox fast, this functions take a bit time to finish it's work, Do we get selection listeners correctly in that case?

**Comment by cbt1** [comment]
> `addSelectionListeners`

`addSelectionListeners` returns a clean-up function that removes the listeners from selections api. Since the clean-up function was not returned inside the useEffect the listeners never was removed.

It should probably just be a custom hook instead of a function that returns a clean-up. That would be easier to use and understand.

**Comment by cbt1** [comment]
@a-m-dev I ended up refactoring this into a custom hook instead for clearity. But that did require a lot more changes in the code.

**Review by a-m-dev — APPROVED** [review]
✅ double great!

**Comment by haxxmaxx** [comment]
I actually had this on my TODO list, should have been in Jira I guess. Great find!

**Pull request merged**
