### PR TITLE
docs(example): use custom theme in mashup

### PR DESCRIPTION
**Pull request by LiKang6688**
Reference:
https://github.com/qlik-oss/nebula.js-examples/tree/main/examples/themes

### CODE REVIEW

**Comment by haxxmaxx** [comment]
This is not a feature. I thought it had something to do with getting themes to work in a mashup, but it is just adding themes to the example

**Comment by LiKang6688** [comment]
> This is not a feature. I thought it had something to do with getting themes to work in a mashup, but it is just adding themes to the example

docs? i am not sure about it.

**Comment by LiKang6688** [comment]
Screenshot 2022-03-08 at 09 49 31
@haxxmaxx which one do you prefer?

**Comment by haxxmaxx** [comment]
good question... docs(example) maybe. Want to avoid feat at least

**Review by haxxmaxx — APPROVED** [review]
I saw that codeclimate is picking this up, we probably want to ignore the whole folder

**Comment by LiKang6688** [comment]
> I saw that codeclimate is picking this up, we probably want to ignore the whole folder

I will ignore the sense-dark-horizon.js file if possible. I see the benefit to keep the quality of mashup examples in place.

**Pull request merged**
