### PR TITLE
fix: line height

### LINKED ISSUE #80: styling panel font size
should be able to consume font sizes set in styling panel, both header and content

### PR DESCRIPTION
**Pull request by haxxmaxx**
Fixes #80

Two more or less identical functions, but waiting with refactoring until we are done with all properties.

### CODE REVIEW

**Review by LiKang6688 — APPROVED** [review]

**Comment by haxxmaxx** [comment]
I'll wait with this until we merge the hover styling, so I can set default constants for those values as well

**Review by LiKang6688 — APPROVED** [review]
Looks good to me.

**Comment by haxxmaxx** [comment]
> I would say it is better to commit to a new PR as the commit here is not relevant to the current PR.

Hmm yeah you're right. I'll actually revert it for better tracking

**Comment by LiKang6688** [comment]
> > I would say it is better to commit to a new PR as the commit here is not relevant to the current PR.
> 
> Hmm yeah you're right. I'll actually revert it for better tracking
👍

**Pull request merged**
