### PR TITLE
feat(translation): all possible to be translated strings

### PR DESCRIPTION
**Pull request by LiKang6688**

### CODE REVIEW

**Review by niekvanstaveren — COMMENTED** [review]
This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build

**Comment by LiKang6688** [comment]
> This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build

Right, gonna use "build:watch": "yarn run locale:generate && rollup -c rollup.config.js -w", 
as the rollup configuration will be deprecated in https://github.com/qlik-oss/sn-table/pull/265.

**Comment by haxxmaxx** [comment]
> > This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build
> 
> Right, gonna use "build:watch": "yarn run locale:generate && rollup -c rollup.config.js -w", as the rollup configuration will be deprecated in #265.

Could we get #265 in first then? It look good to me, but I'm not comfortable approving it. Can you ping Tobias? SInce he wrote that stuff for a different repo.

**Comment by LiKang6688** [comment]
> > > This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build
> > 
> > 
> > Right, gonna use "build:watch": "yarn run locale:generate && rollup -c rollup.config.js -w", as the rollup configuration will be deprecated in #265.
> 
> Could we get #265 in first then? 265 looks good to me, but I'm not comfortable approving it. Can you ping Tobias? SInce he wrote that stuff for a different repo.

Sure. I gonna ping Tobias

**Comment by niekvanstaveren** [comment]
> > > > This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build
> > > 
> > > 
> > > Right, gonna use "build:watch": "yarn run locale:generate && rollup -c rollup.config.js -w", as the rollup configuration will be deprecated in #265.
> > 
> > 
> > Could we get #265 in first then? 265 looks good to me, but I'm not comfortable approving it. Can you ping Tobias? SInce he wrote that stuff for a different repo.
> 
> Sure. I gonna ping Tobias

Not sure why this would be not comfortable since it only changes the build:watch command. Was more concerned with the addition to the build command. Have we fully tested the build and seen that the translations were added correctly?

This step is just a continuation of the previous PR

**Comment by LiKang6688** [comment]
> > > > > This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build
> > > > 
> > > > 
> > > > Right, gonna use "build:watch": "yarn run locale:generate && rollup -c rollup.config.js -w", as the rollup configuration will be deprecated in #265.
> > > 
> > > 
> > > Could we get #265 in first then? 265 looks good to me, but I'm not comfortable approving it. Can you ping Tobias? SInce he wrote that stuff for a different repo.
> > 
> > 
> > Sure. I gonna ping Tobias
> 
> Not sure why this would be not comfortable since it only changes the build:watch command. Was more concerned with the addition to the build command. Have we fully tested the build and seen that the translations were added correctly?
> 
> This step is just a continuation of the previous PR

@niekvanstaveren  I think that Max is not comfortable in approving #256.  It would be good that we get #256 in first.

**Comment by LiKang6688** [comment]
> > > > This will now break the build:watch command since the all.json file is not present. Like mentioned before you probably want to add the creation of all.json in the rollup configuration so this will happen every time you build
> > > 
> > > 
> > > Right, gonna use "build:watch": "yarn run locale:generate && rollup -c rollup.config.js -w", as the rollup configuration will be deprecated in #265.
> > 
> > 
> > Could we get #265 in first then? 265 looks good to me, but I'm not comfortable approving it. Can you ping Tobias? SInce he wrote that stuff for a different repo.
> 
> Sure. I gonna ping Tobias

@haxxmaxx Tobias said that it looks good.

**Review by tklkan — APPROVED** [review]

**Review by ashrles — APPROVED** [review]

**Review by niekvanstaveren — APPROVED** [review]

**Pull request merged**
